app_mapping = {
    "spotify": "C:\\Users\\sujal\\AppData\\Roaming\\Spotify\\Spotify.exe",
    "chrome": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "notepad": "notepad.exe",
    "calculator": "calc.exe",
    "vlc": "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
    "valorant": "C:\\Riot Games\\Riot Client\\RiotClientServices.exe",
    "discord": "C:\\Users\\sujal\\AppData\\Local\\Discord\\app-1.0.9003\\Discord.exe",
    "youtube": r'"C:\\Program Files (x86)\\Microsoft\Edge\\Application\\msedge_proxy.exe"  --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml --app-url=https://www.youtube.com/?feature=ytca --app-launch-source=4',
    "whatsapp": "C:\\Program Files\\WindowsApps\\5319275A.WhatsAppDesktop_2.2546.3.0_x64__cv1g1gvanyjgm\\WhatsApp.exe",
    "firefox": "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
    "bluestacks": "C:\\Program Files (x86)\\BlueStacks\\Bluestacks.exe",
    "telegram": "C:\\Users\\sujal\\AppData\\Local\\Telegram Desktop\\Telegram.exe",
    "settings": "C:\\Users\\sujal\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Settings\\Settings.exe",
    "power_shell": "powershell.exe",
    "command_prompt": "cmd.exe",
    "terminal": "C:\\Users\\sujal\\AppData\\Local\\Microsoft\\WindowsApps\\WSL.exe",
    "file_explorer": "explorer.exe",
    "system_monitor": "C:\\Windows\\System32\\taskmgr.exe",
    "registry_editor": "regedit.exe",
    "store": "C:\\Users\\sujal\\AppData\\Roaming\\Microsoft\\Windows\\StorageExplorer\\StorageExplorer.exe",
    "camera": "USB\\VID_0C45&PID_6730&MI_00\\6&33E3B4BF&0&0000",
    "photos": "C:\\Program Files\\WindowsApps\\Microsoft.Windows.Photos_2025.11030.12002.0_x64__8wekyb3d8bbwe\\Photos.exe",
    "music": "C:\\Users\\sujal\\OneDrive\\Desktop\\Music.exe",
    "movies": "C:\\Users\\sujal\\OneDrive\\Desktop\\Movies.exe",
    "documents": "C:\\Users\\sujal\\OneDrive\\Desktop\\Documents.exe",
    "downloads": "C:\\Users\\sujal\\OneDrive\\Desktop\\Downloads.exe",
    "videos": "C:\\Users\\sujal\\OneDrive\\Desktop\\Videos.exe",
    "code": "C:\\Users\\sujal\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
    "notepad++": "C:\\Program Files (x86)\\Notepad++\\notepad++.exe",
    "notepad++_x64": "C:\\Program Files\\Notepad++\\notepad++.exe",
    "code_x64": "C:\\Users\\sujal\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
    "linkedin":"C:\\Program Files\\WindowsApps\\7EE7776C.LinkedInforWindows_3.0.42.0_x64__w1wdnht996qgy\\LinkedIn.exe",
    "notion":"C:\\Users\\sujal\\AppData\\Local\\Programs\\Notion.exe",
    "perplexity":"C:\\Users\\sujal\\AppData\\Local\\Programs\\Perplexity\\Perplexity.exe"
    # Add more apps with their paths
}